name: nomirrorsmap
version: 1.0.0-dev17
author: jrote1<jrote1@me.com>
description: A multipurpose mapping library
homepage: https://github.com/jrote1/nomirrorsmap.dart
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  barback: '>=0.12.0 <0.17.0'
  code_transformers: '>=0.2.3 <0.3.0'
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: any
transformers:
- nomirrorsmap
