name: nomirrorsmap
dependencies:
  barback: any
  LiveScoring:
    path: D:/SpawtzLiveScoring/Src/DartProjects/LiveScoring
transformers:
  nomirrorsmap:
    libraries: ["lib/entites/entites.dart"]
    packages: ["shared"]