name: nomirrorsmap
version: 0.0.18+2
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  barback: any
  code_transformers: any
  path: any
dev_dependencies:
  unittest: any
transformers:
  - nomirrorsmap
