name: nomirrorsmap
version: 0.0.7
dependencies:
  barback: any
dev_dependencies:
  unittest: any
#transformers:
#  - nomirrorsmap:
#      libraries: ["lib/entites/entites.dart"]
#      packages: ["shared"]
