name: nomirrorsmap
version: 1.0.0
author: jrote1<jrote1@me.com>
description: A multipurpose mapping library
homepage: https://github.com/jrote1/nomirrorsmap.dart
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  code_transformers: any
  dart_style: any
  path: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: any
