name: nomirrorsmap
dependencies:
  barback: any
  LiveScoring:
    path: D:/SpawtzLiveScoring/Src/DartProjects/LiveScoring
dev_dependencies:
  unittest: any
transformers:
  - nomirrorsmap:
      libraries: ["lib/entites/entites.dart"]
      packages: ["shared"]